version: "3.9"

services:
  full-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: full-api
    ports:
      - "3333:3333"
    depends_on:
      - postgres

  postgres:
    image: "bitnami/postgresql:latest"
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: full-postgres-api
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
